"""
Generates a formatted markdown daily digest from a list of HN stories.
"""

import os
from datetime import datetime, timezone


HN_ITEM_URL = "https://news.ycombinator.com/item?id={}"


def _format_story(rank: int, story: dict) -> str:
    """Format a single story as a markdown list item."""
    title = story.get("title", "No title")
    url = story.get("url") or HN_ITEM_URL.format(story["id"])
    score = story.get("score", 0)
    author = story.get("by", "unknown")
    comments = story.get("descendants", 0)
    hn_link = HN_ITEM_URL.format(story["id"])

    return (
        f"{rank}. **[{title}]({url})**\n"
        f"   ↑ {score} points · by {author} · "
        f"[{comments} comments]({hn_link})\n"
    )


def generate_report(stories: list[dict], date: datetime | None = None) -> str:
    """
    Build a full markdown report string from a list of story dicts.

    Args:
        stories: list of story dicts from fetcher.fetch_top_stories()
        date:    report date (defaults to UTC now)

    Returns:
        Markdown string ready to write to a file.
    """
    if date is None:
        date = datetime.now(timezone.utc)

    date_str = date.strftime("%A, %d %B %Y")
    timestamp = date.strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# 📰 Hacker News Daily Digest — {date_str}\n",
        f"> Generated: {timestamp}  ",
        f"> Stories: {len(stories)} top posts\n",
        "---\n",
    ]

    for i, story in enumerate(stories, start=1):
        lines.append(_format_story(i, story))

    lines += [
        "---\n",
        "_Auto-generated by [auto-news-scraper](https://github.com/ByteMe-UK/auto-news-scraper) "
        "· Powered by the [HackerNews API](https://github.com/HackerNews/API)_\n",
    ]

    return "\n".join(lines)


def save_report(content: str, output_dir: str = "reports") -> str:
    """
    Save the report to reports/YYYY-MM-DD.md.

    Returns the path of the saved file.
    """
    os.makedirs(output_dir, exist_ok=True)
    filename = datetime.now(timezone.utc).strftime("%Y-%m-%d") + ".md"
    path = os.path.join(output_dir, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path
